pages: []
29Fd: []
29Fw: []

30Ga:
  - from: docs/Onboarding/
    as: 01-Onboarding
    ignore:
      - _category_.yml

  - from: docs/OF-BYOD-Basics-29/
    as: 02-BYOD
    ignore:
      - _category_.yml
      - 00-Szenarien.mdx

  - from: docs/OF-Programmieren-1/
    as: 03-Programmieren-1
    ignore:
      - _category_.yml
      - index.mdx
      - 02-py-intro
      - 03-repeat
      - 04-errors
      - 05-functions
      - 06-parameters
      - 07-Variablen
      - 08-Verzweigungen
      - 09-While
      - 10-Rueckgabewerte
      - 12-rekursion
      - 16-modulo
      - 15-Gruefnisch
      - 20-commands
      - 21-mistakes.mdx
      - 30-Repefragen
      - 50-Test
      - 51-Tests.mdx

30Gc: []
30Gf: []
30mU: []